env:
  commonjs: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  indent: ['error', 2]
  quotes: ['error', 'single']
  semi: ['error', 'always']
  comma-dangle: ['error', 'always-multiline']
  space-before-function-paren: ['error', 'never']
